CREATE TABLE USER(
	ID INT AUTO_INCREMENT,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(60),
	NAME VARCHAR(50),
    RoleID INT,
    RULETA_ID INT,
    ESTADISTICAS_PERSONALES_ID INT
);

CREATE TABLE ROLE(
ID INT AUTO_INCREMENT,
NAME VARCHAR(15),
UserID INT
);

CREATE TABLE USER_ROLES(
Users_ID INT,
Roles_ID INT
);

CREATE TABLE ESTADISTICAS_PERSONALES(
	ID INT AUTO_INCREMENT,
	 DINERO_GASTADO_PRIMITIVAS FLOAT,
     DINERO_GANADO_PRIMITIVAS FLOAT,
     BENEFICIO_PRIMITIVAS FLOAT,
     APUESTAS_PRIMITIVAS_JUGADAS FLOAT,
     BENEFICIO_MEDIO_PRIMITIVAS FLOAT,
    
     DINERO_GASTADO_EUROMILLONES FLOAT,
     DINERO_GANADO_EUROMILLONES FLOAT,
     BENEFICIO_EUROMILLONES FLOAT,
     APUESTAS_EUROMILLONES_JUGADAS FLOAT,
     BENEFICIO_MEDIO_EUROMILLONES FLOAT,
    
     DINERO_GASTADO_RULETAS FLOAT,
     DINERO_GANADO_RULETAS FLOAT,
     BENEFICIO_RULETAS FLOAT,
     APUESTAS_RULETAS_JUGADAS FLOAT,
     BENEFICIO_MEDIO_RULETAS FLOAT,
    USER_ID INT
);

CREATE TABLE PRIMITIVA(
ID INT AUTO_INCREMENT,
RESULTADO0 INT,
RESULTADO1 INT,
RESULTADO2 INT,
RESULTADO3 INT,
RESULTADO4 INT,
RESULTADO5 INT,
COMPLEMENTARIO INT,
REINTEGRO INT
);

CREATE TABLE EUROMILLONES(
ID INT AUTO_INCREMENT,
RESULTADO0 INT,
RESULTADO1 INT,
RESULTADO2 INT,
RESULTADO3 INT,
RESULTADO4 INT,
ESTRELLA0 INT,
ESTRELLA1 INT
);

CREATE TABLE RULETA(
ID INT AUTO_INCREMENT,
NUMERO INT,
COLOR VARCHAR(5),
USER_ID INT
);


ALTER TABLE USER
ADD FOREIGN KEY (RoleID) REFERENCES ROLE(ID);

ALTER TABLE ROLE
ADD FOREIGN KEY (UserID) REFERENCES USER(ID);