CREATE TABLE USER(
	ID INT AUTO_INCREMENT,
	USERNAME VARCHAR(50),
	PSSWRD VARCHAR(50)
);

CREATE TABLE PRIMITIVA(
ID INT AUTO_INCREMENT,
RESULTADO0 INT,
RESULTADO1 INT,
RESULTADO2 INT,
RESULTADO3 INT,
RESULTADO4 INT,
RESULTADO5 INT,
COMPLEMENTARIO INT,
REINTEGRO INT
);

CREATE TABLE EUROMILLONES(
ID INT AUTO_INCREMENT,
RESULTADO0 INT,
RESULTADO1 INT,
RESULTADO2 INT,
RESULTADO3 INT,
RESULTADO4 INT,
ESTRELLA0 INT,
ESTRELLA1 INT
);